export enum AvailableElements {
  TOP_FIRSTNAME,
  TOP_LASTNAME,
  TOP_JOB_TITLE,
  TOP_SIZE,
  TOP_BREAKLINE,
  TOP_PLACEMENT_NAME,
  TOP_PLACEMENT_CONTACT,
  TOP_PLACEMENT_PHOTO,
}

export enum AvailableSections {
  NAME_AND_TITLE,
  CONTACT,
  PHOTO,
}
